name: Build & Push Multiarch Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'static/**'
      - '.github/workflows/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/sofacela/weather-app
      CACHE_REPO: sofiialaba/cache

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u sofacela --password-stdin

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u sofiialaba --password-stdin

    - name: Build and push image (multiarch)
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ghcr.io/sofacela/weather-app:latest
          ghcr.io/sofacela/weather-app:multiarch
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=sofiialaba/cache:weather-app
        cache-to: type=registry,ref=sofiialaba/cache:weather-app,mode=max
        build-args: |
          OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}

    - name: Scan image for CVEs using Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/sofacela/weather-app:multiarch'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
        exit-code: 1
